### ISSUE TITLE
Slow parsing of big text files

### ISSUE THREAD

**Issue by Alexander-Minyushkin** [codebox/markov-text#1]
`markov.py parse` with depth=2 takes several hours for ~5MB file on Windows 7, Intel(c) Core(TM) i3-3210 CPU @ 3.2GHz

## Possible solution that take about a minute:

In [cygwin](https://www.cygwin.com/) run following command:
```
time cat input.txt | sed 's/\./ $ ^/g' | tr " " "\n" | 
awk 'BEGIN{prev="^ ";OFS=","}{print prev, $0; prev=$0}'  | sort | uniq -c | sort -gr | 
awk 'BEGIN{OFS=","}{print $2,$1}' | 
sed '/\$\,\^/d' | sed '/\^\,\$/d' > word.csv

real    0m14.873s
user    0m16.907s
sys     0m0.228s
```
You will get file **word.csv**

Then in new database you have to create required tables:
```
CREATE TABLE word (word1 varchar(255), word2 varchar(255), count int);
CREATE TABLE param (name varchar(255), value int);
INSERT INTO `param` VALUES ('depth',2);
```

Import from CSV file : **words.csv**
And then

`CREATE INDEX i_word ON word (word1, word2);`

DB is ready to run `markov.py gen` with depth=2

## Explanation:
Command line pipe is modification of ["A Linux one-liner to count the unique words in a set of files"](http://doofussoftware.blogspot.ru/2012/07/a-linux-one-liner-to-count-unique-words.html) 
`sed 's/\./ $ ^/g'` - this part inserts default start and end symbols (defined in parse.py)
`awk 'BEGIN{prev="^ ";OFS=","}{print prev, $0; prev=$0}' ` - create pair of words. 
**You need to change this part for depth different from 2.**
`awk 'BEGIN{OFS=","}{print $2,$1}'` - proper order of outputs.
`sed '/\$\,\^/d' | sed '/\^\,\$/d' ` - cleanup.

**Comment by codebox** [comment]
Thanks for the useful notes, although I'm puzzled about why it took so long on your system. I ran some tests on my i7 2.2GHz MacBook Pro, a 5.6MB file with depth=2 took just over 2 minutes:

real	2m16.736s
user	0m44.305s
sys	0m56.187s

I found a noticeable improvement moving the database commit statement to the end of the parse function so it gets called only once, rather than after each sentence. With this change in place the time for the large file went down to about 30 seconds:

real	0m32.417s
user	0m29.614s
sys	0m2.672s

I think this improvement is big enough to be worth including the change here, so thanks again for bringing this to my attention. I would be interested to know how much difference moving the commit statement makes on your system.
